import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E6F7F7",
    paddingTop: 10,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    textAlign: "left",
    padding: 15,
  },
  filledCircle: {
    backgroundColor: "gray",
  },
  btnAgregar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#0A84FF",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    right: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    padding: 15,
    marginHorizontal: 10,
    marginVertical: 5,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  textCompleted: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    textAlign: "left",
    textDecorationLine: "line-through",
    textDecorationColor: "Green",
  },
  circle: {
    width: 25,
    height: 25,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "gray",
    marginRight: 15,
  },
  textContainer: {
    flex: 1,
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  subtitle: {
    fontSize: 14,
    color: "gray",
  },
  date: {
    color: "#0A84FF",
    fontWeight: "bold",
  },
  bottomButtonsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  filterButton: {
    position: "absolute", // Posición absoluta para flotar
    bottom: 20, // Distancia desde la parte inferior
    alignSelf: "center", // Centrado horizontal
    backgroundColor: "#70b2b2",
    padding: 15,
    borderRadius: 30,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  filterButtonText: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",
  },
  detailContainer: {
    backgroundColor: "#f8f8f8",
    borderRadius: 10,
    padding: 20,
  },
  label: {
    fontSize: 18,
    fontWeight: "600",
    marginTop: 10,
    color: "#555",
  },
  value: {
    fontSize: 16,
    marginBottom: 15,
    color: "#333",
    paddingLeft: 10,
  },
  containerView: {
    flex: 1,
    padding: 20,
    backgroundColor: "#E6F7F7",
  },
  button: {
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
  },
});
